/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static int multiply(int a, int b) {
        return a * b;
    }

    public static void main(String[] args) {
        System.out.println("Hello, Jenkins & JUnit!");
    }
}

